trigger:
- main

pool:
  name: 'comp367quiz4'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: 'sdk'

- script: dotnet restore
  displayName: 'dotnet restore'

- script: dotnet build --configuration Release
  displayName: 'dotnet build'

- script: dotnet test
  displayName: 'dotnet test'

- script: dotnet publish --configuration Release --output publish
  displayName: 'dotnet publish'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'publish'
    ArtifactName: 'drop'
    publishLocation: 'Container'